---
title: "Final Project"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(dplyr)
library(tidyverse)
library(randomForest)
library(knitr)
library(caret)
library(tree)
library(janitor)
library(glmnet)
library(splines)
library(pls)
library(boot)
library(plotly)
library(ggplot2)
library(cluster)
library(factoextra)
library(grid)
library(class)
library(parallel)
library(doParallel)
```

# Data Exploration
```{r}
releg <- read_csv("Relegations.csv")
income <- read_csv("Income_PL.csv")
data <- read_csv("Soccer Data.csv")
releg

releg2 <- releg %>% gather(Games, Amount, c("Wins", "Draws", "Loses"))


## Create a graph for W/D/L per team per Season
posChart <- ggplot(releg2, aes(x = Team, label = `Final Ranking`)) +
         geom_col(aes(y = Amount, fill = Games),position = "dodge") +
         theme(axis.text.x = element_text(angle = 45)) +
         scale_y_continuous(breaks = c(5, 10, 15, 20, 25, 30)) 


ggplotly(posChart)

```

# Modeling Part 2 - Random Forest - Predicting H, D, A
```{r}
data <- read_csv("Soccer Data.csv")

# Removing clearly correlated data and/or unwanted predictors
data2 <- data %>% select(-HTG, -ATG, -Date, -Day, -Month, -Year, -AY, -HY)
data2

#Setting up Predictors
colPreds <- c("Matchday", "HomeTeam", "AwayTeam", "HS", 
              "AS", "HST", "AST", "HF", "AF", "HC", "AC", "HR", "AR")

#Train/Test data - 2013-2018 Seasons Train, 2018-2019 Season Test
xTrain <- data2[1:1900, colPreds]
xTest <- data2[1901:2280, colPreds]

yTrain <- as.factor(data2[1:1900,]$RES)
yTest <- as.factor(data2[1901:2280,]$RES)

set.seed(1234)

# Checking Mean Decrease Accuracy

model <- randomForest(xTrain, yTrain,
                      mtry = 2,
                      ntree = 500,
                      strata = yTrain, 
                      importance = TRUE)

imp <- as_tibble(importance(model, type = 2))
imp <- cbind(colPreds, imp)
imp <- imp %>% rename(Predictors = colPreds) %>% arrange(desc(MeanDecreaseGini))

ggplot(imp, aes(x = reorder(Predictors, MeanDecreaseGini), y = MeanDecreaseGini)) +
  geom_bar(fill = "darkgreen", stat = "identity") +
  coord_flip() +
  labs(title = "Random Forests - Rank by Importance", 
       x = "Predictors", y = "Mean Decrease in Gini")
```

```{r, warning=FALSE}
## Running Random Forest

set.seed(1234)

## Random Forest
trctrl <- trainControl(method = "repeatedcv", number = 5, repeats = 1, allowParallel = TRUE)

model <- train(xTrain, yTrain,
                     method = "rf",
                     strata = yTrain,
                     tuneLength = 3,
                     trControl = trctrl)

plot(model$finalModel)

rfPred <- predict(model, xTest)

table(rfPred, yTest)
tbl <- table(rfPred, yTest)

# Overall Accuracy
mean(rfPred == yTest)

#Away Win Accuaracy
tbl[1,1]/(tbl[1,1] + tbl[1,2] + tbl[1,3])

#Home Win Accuracy
tbl[3,3]/(tbl[3,3] + tbl[3,1] + tbl[3,2])

#Draw Accuracy
tbl[2,2]/(tbl[2,2] + tbl[2,1] + tbl[2,3])

#Overall Misclassification
mean(rfPred != yTest)

#Away Misclass
(tbl[1,2] + tbl[1,3])/(tbl[1,1] + tbl[1,2] + tbl[1,3])

#Home Win Misclass
(tbl[3,1] + tbl[3,2])/(tbl[3,3] + tbl[3,1] + tbl[3,2])

#Draw Misclass
(tbl[2,1] + tbl[2,3])/(tbl[2,2] + tbl[2,1] + tbl[2,3])

#Creating 
overall <- as_tibble(cbind(xTest$HomeTeam, xTest$AwayTeam, yTest, rfPred))
overall$yTest <- ifelse(overall$yTest == "1", "A", 
                        ifelse(overall$yTest == "2", "D", "H"))
overall$rfPred <- ifelse(overall$rfPred == "1", "A", 
                        ifelse(overall$rfPred == "2", "D", "H"))
overall <- overall %>% mutate(Correct = ifelse(yTest == rfPred, "Yes", "No")) %>% rename("Home Team" = V1, "Away Team" = V2, "Actual Result" = yTest, "Predicted Result" = rfPred)
overall
```


# Modeling Part 1 - kNN
```{r}
## k Nearest Neighbors
releg <- read_csv("Relegations.csv")
releg3 <- releg %>% select(Wins, Draws, Loses, `Goal Difference`, `Relegated - Post`)
releg3 <- clean_names(releg3)

##Train/Test data - 2013-2016 Seasons Train, 2016-2019 Season Test
train <- releg3[1:60,]
test <- releg3[61:120,]

trainMat <- train %>% select(-relegated_post) %>% as.matrix()
testMat <- test %>% select(-relegated_post) %>% as.matrix()
trainY <- as.matrix(train$relegated_post)


## CHANGABLE - Picking the K value - max of 18 that shows both yes and no
knnPred <- knn(trainMat, testMat, trainY, k = 9)
tbl <- table(knnPred, test$relegated_post)
tbl <- data.frame(tbl[,1:2])
tbl <- tbl %>% rename(Predicted = knnPred, Actual = Var2, Frequency = Freq)
tbl

## Accuracy
mean(knnPred == test$relegated_post)

## Misclassification
mean(knnPred != test$relegated_post)

modelMatrix <- matrix(c(paste0(round(mean(knnPred == test$relegated_post)*100, 2), "%"), 
         paste0(round(mean(knnPred != test$relegated_post)*100, 2), "%")), 
         ncol = 2, nrow = 1,
       dimnames = list(c("k-Nearest Neighbors"), 
                       c("Accuracy", "Misclassification Rate")))
modelMatrix
## Set up Predictions for K = 9
set.seed(1234)

trctrl <- trainControl(method = "repeatedcv", number = 5, repeats = 1)

knnFit <- train(relegated_post ~ ., data = train, method = "knn",
                trControl = trctrl, 
                tuneLength = 3
                )



## CHANGABLE - Test out predictions
predKnn <- predict(knnFit, newdata = data.frame(wins = 15, loses = 10, draws = 5, goal_difference = 15))

ifelse(predKnn == "No", "No", "Yes")

```

# Graph KNN
```{r}
# Create a dataframe to simplify charting
plot.df <-  data.frame(test, predicted = knnPred)

# Use ggplot
# First use Convex hull to determine boundary points of each cluster
plot.df1 <-  data.frame(x = plot.df$wins, 
                      y = plot.df$loses, 
                      predicted = plot.df$predicted)

find_hull <-  function(df) df[chull(df$x, df$y), ]

boundary <-  plyr::ddply(plot.df1, .variables = "predicted", .fun = find_hull)


gplot <- ggplot(plot.df, aes(wins, loses, color = predicted, fill = predicted)) + 
  geom_polygon(data = boundary, aes(x,y), alpha = 0.5) +
  geom_point(size = 3)


ggplotly(gplot)
```

# Cluster - k Means
```{r}
releg <- read_csv("Relegations.csv")
releg <- releg %>% rename(Club = Team)

join <- releg %>% filter(Season == "13-14") %>% select(Club, `Final Ranking`, Wins, Draws, Loses, `Goals For`, `Goals Against`)


join <- join %>% remove_rownames() %>% column_to_rownames(var = unique("Club"))

join <- scale(join)

distance <- get_dist(join)

fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))

## Can change centers and nstart
k2 <- kmeans(join, centers = 4, nstart = 10)

fviz_cluster(k2, data = join) +
  scale_x_continuous(limits = c(-5, 5)) +
  scale_y_continuous(limits = c(-3,3)) + 
  ggtitle("k = 4")
```


# Scroll Data
```{r}
data <- read_csv("Soccer Data.csv")
data <- data %>% filter(Season == "13-14", HomeTeam == "Manchester United" | AwayTeam == "Manchester United") %>% select(-Day, -Month, -Year, -GD)
data <- data %>% unite("FinalScore", HTG, ATG, sep = "-")
data

kable(data)

## Make a Key for the Data set Names 
```

# Other
```{r}
releg <- read_csv("Relegations.csv")
releg <- releg %>% rename(Club = Team) %>% mutate(RD = `Final Ranking` - EndJan) %>% select(Season, Club, RD, `Final Ranking`)

income <- read_csv("Income_PL.csv")

join <- full_join(income, releg, by = c("Season", "Club"))
join <- join %>% filter(Season == "13-14", Transfer == "Winter") %>% select(Season, Club, `Final Ranking`, RD, Expenditure, Transfer) %>% arrange(`Final Ranking`)



par(mar=c(5.1, 4.1, 2.5, 4))

barplot(join$Expenditure ~ join$Club, xlab = "", ylab = "", las = 2, ylim = c(0,60), xaxt = "n", col = "red") 

par(new = TRUE) 
plot(join$`Final Ranking`,join$RD, type = "o", xaxt = "n", yaxt = "n", xlab = "", ylab = "", col = "blue", lwd = 2, pch = 15) 

abline(h = 0, lty = 2, col = "blue") 

text(x = 1:20,
     y = par("usr")[3] - 0.50,
     labels = join$Club,
     xpd = NA, 
     srt = 50, 
     cex = 0.75, 
     adj = .95) 

axis(side = 4, at = pretty(range(join$RD))) 
mtext("League Position +/-", side = 4, line = 2, cex = .90) 
mtext("Transfer Spending (in Millions)", side = 2, line = 2.5, cex = .90) 
mtext("Winter Transfer Expenditure", side = 3, line = 1)
```


